name: Frontend workflow

on:
  push:
    branches:
      - feature-cicd

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: react development
        uses: actions/checkout@v2
      - name: Use Node.js 17.x
        uses: actions/setup-node@v1
        with:
          node-version: 17.x
      - run: npm install
      - name: Deploy to Heroku server
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: 'vanity-swiggy-for-salons-fe'
          heroku_email: 'axcal16@gmail.com'
